### ISSUE TITLE
Votekick/ban

### ISSUE THREAD

**Issue by aletheist** [josephdunn/willie-modules#26]
A module to do a votekick/ban would be useful.

I would envision it as requiring 50%+1 of currently talking voiced or higher users to kick a person.

We could also have it do a timed AKICK entry of, say, an hour for a 60%+1 of active voiced or higher users.

This might be difficult because WorfBot would need to keep track of what constitutes a "currently active" user.

**Comment by Ganon11** [comment]
We could possibly have a function that listens to every line said in a channel, and adds the username and current to a map of <username, time>. When a .votekick <Identifier> command comes in, check the total votes against that username compared to the count of users whose timestamps are within 10 minutes.

Inefficient, but probably fairly effective. We can mark the listening function as low priority (I think there's a sopel attribute to indicate thread priority).

**Comment by aletheist** [comment]
We could also have users use something like .ballot to indicate they intend to vote.

**Comment by aletheist** [comment]
Or,

`votekick <user>` along with a `votekeep <user>`

That one is probably workable. It would work over PM or in public, right?

**Comment by Ganon11** [comment]
It probably wouldn't work over PM, simply because Willie/Sopel/WorfBot supports multiple channels - how would it know from which channel to kick/ban the user?

**Comment by aletheist** [comment]
I don't actually like the `.votekeep` idea. It'd be too easy for a small number of people with an opinion to kick someone when there's not actually consensus. I'd prefer the inefficient but imo better strategy of tracking messages to see who is active.

**Comment by aletheist** [comment]
After talking to jbermudes, we could instead vote to +m or +r the channel for a period of time.

**Comment by Ganon11** [comment]
There's some cleanup that can be done, but #30 is a good starting point for this implementation. Closing this in favor of more pointed issues.
