### ISSUE TITLE
denom check ident

### ISSUE THREAD

**Issue by aletheist** [josephdunn/willie-modules#29]
We might want to enforce that a user be idented and own a nick before they can change the denomination. This may involve getting information from NickServ or `whois`

**Comment by Ganon11** [comment]
I looked through Sopel's codebase, but couldn't find a convenience function to determine if a nick is authenticated/identified with NickServ. We should be able to do it by bot.action("msg") or something similar, and asking NickServ ourself, but we'd have to parse the response.

We'd also need to check for the case of an identify'd user changing to another user's nick - would NickServ still claim they are identified? a.k.a.

```
< mstark> /nick aletheist
< aletheist> .denom A Silly Person
(NickServ claims "aletheist" is identified, since "aletheist" is ident'd to mstark)
< aletheist> /nick mstark
< mstark> the perfect crime!
```

**Comment by josephdunn** [comment]
They have an open issue about it. Basically there's no easy way to do it,
and there's a proposed IRC protocol extension that would make it easy, but
no IRC servers support it yet. I'm going to play around with something that
queries NickServ about it using INFO.

**Comment by josephdunn** [comment]
If you guys could try to break what I just committed, that'd be great. If we can't break it then I'll close the issue.

**Comment by Ganon11** [comment]
I had a showerthought about this.

What if we associated denomination/flair with the account name rather than the nick?

.denom <nick> first queries Nickserv to find out the account name. It then checks the database/bot.memory for the account name's flair, then responds accordingly. a.k.a.

```
*mstark is now known as Ganon11*
<@Ganon11> .denom
// WorfBot asks what the account name is for nick Ganon11, finds that it is *mstark*
// WorfBot checks bot.memory['denom']['mstark'] and finds "Orthodox-curious Nondenominational Christian attending a Baptist Church"
<@WorfBot> Ganon11 is Orthodox-curious Nondenominational Christian attending a Baptist Church
*mstark is now known as aletheist*
<@aletheist> .denom
// Same thing - WorfBot finds "aletheist" is actually account *mstark* and checks/sets mstark's denom
```

* Pros
 * Keeps someone from setting another person's denom, unless they know the NickServ pass (in which case that person has bigger problems)
 * People whose nick doesn't match their account can still use it (Scully/Buffy/blah)
* Cons
 * In the above scenario, it shows "aletheist is mstark's special-flower-denomination", which can be confusing since I'm impersonating aletheist
 * Requires user to be authed to NickServ (not sure if Con, and also is currently the case)

**Comment by aletheist** [comment]
This strategy sounds good to me.

**Comment by aletheist** [comment]
I tried to implement @Ganon11's suggestion yesterday. It does not work because when you run `NickServ INFO` on a nick that has been absconded with, it looks no different than if it was the real user. 

```
17:45:56 freenode -- You are now known as Henry_the_Butler
17:45:56 freenode -- NickServ (NickServ@services.): This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>.
17:46:04 freenode -- MSG(nickserv): info Henry_the_Butler
17:46:04 freenode -- NickServ (NickServ@services.): Information on Henry_the_Butler (account Henry_the_Butler):
17:46:04 freenode -- NickServ (NickServ@services.): Registered : Mar 08 16:45:04 2013 (3y 25w 4d ago)
17:46:04 freenode -- NickServ (NickServ@services.): Last addr  : ~KM1604@96-40-85-126.dhcp.aldl.mi.charter.com
17:46:04 freenode -- NickServ (NickServ@services.): Last seen  : Aug 24 13:06:39 2016 (1w 2d 8h ago)
17:46:04 freenode -- NickServ (NickServ@services.): User seen  : now
17:46:04 freenode -- NickServ (NickServ@services.): Flags      : HideMail
17:46:04 freenode -- NickServ (NickServ@services.): *** End of Info ***
```

**Comment by aletheist** [comment]
I went to implement this idea today and realized it has the same weakness as `NickServ Info` -- you can't tell if a person actually owns the account. The only way to know that is to have the entire list of nicks belonging to an account, and you can only get that for your own nick, not others'.

**Comment by aletheist** [comment]
PR #47 fixes this as best as I can think of. Do we want to close this or leave it open?
